on:
  issues:
    types: [labeled]

env:
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_ISSUES_WEBHOOK }}

jobs:
  labelNotify:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: notify
        if: > 
          github.event.label.name == 'enhancement' 
          || github.event.label.name == 'bug' 
          || github.event.label.name == 'help wanted'
        uses: Ilshidur/action-discord@master
        with:
          args: "[${{ github.event.issue.title }}](<${{ github.event.issue.html_url }}>) added `${{ github.event.label.name }}` label"
